#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  type-aliases-package: com.zih.springboot.entity
  mapper-locations: classpath:mapper/*.xml
  config-location:  classpath:mybatis-config.xml


---

#开发配置
spring:
  profiles: dev
#数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/world?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Blusseliu89
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
#端口号
server:
  port: 80
#自定义的属性，指定了一个路径，注意要以/结尾
